AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Dado um cliente, obtém as informações em cache (redis), sem autenticação'
Resources:
  getclientposition:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: 'Dado um cliente, obtém as informações em cache (redis), sem autenticação'
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/client/{id}'
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Layers:
        - ''
